// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251210155014_empAdded")]
    partial class empAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Appointment.Meeting", b =>
                {
                    b.Property<Guid>("MeetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActiveMeeting")
                        .HasColumnType("bit");

                    b.Property<int?>("CalculatedPrice")
                        .HasColumnType("int");

                    b.Property<bool>("ConfirmedByAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmedByUser")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FinishDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ForCarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ForCarSPZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartingDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("StartingWorkingDayDayDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MeetId");

                    b.HasIndex("StartingWorkingDayDayDayId");

                    b.ToTable("MeetingsTable");
                });

            modelBuilder.Entity("Domain.Models.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HourlyBase")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Models.Operation.Procedure", b =>
                {
                    b.Property<Guid>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MeetingMeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakeWindows")
                        .HasColumnType("int");

                    b.Property<bool>("fixedPrice")
                        .HasColumnType("bit");

                    b.HasKey("ProcedureId");

                    b.HasIndex("MeetingMeetId");

                    b.ToTable("ProceduresTable");
                });

            modelBuilder.Entity("Domain.Models.ServiceSetting.ServiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BasePricePerWindow")
                        .HasColumnType("int");

                    b.Property<int>("BaseWindowInMinutes")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Morning", "Domain.Models.ServiceSetting.ServiceSettings.Morning#Shift", b1 =>
                        {
                            b1.Property<TimeOnly>("finishTime")
                                .HasColumnType("time")
                                .HasColumnName("MorningFinishTime");

                            b1.Property<TimeOnly>("startTime")
                                .HasColumnType("time")
                                .HasColumnName("MorningStartTime");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("WholeDay", "Domain.Models.ServiceSetting.ServiceSettings.WholeDay#Shift", b1 =>
                        {
                            b1.Property<TimeOnly>("finishTime")
                                .HasColumnType("time")
                                .HasColumnName("WholeDayFinishTime");

                            b1.Property<TimeOnly>("startTime")
                                .HasColumnType("time")
                                .HasColumnName("WholeDayStartTime");
                        });

                    b.HasKey("Id");

                    b.ToTable("SettingsTable");
                });

            modelBuilder.Entity("Domain.Models.Termin.WorkingDay", b =>
                {
                    b.Property<Guid>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("ShiftString")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("DayId");

                    b.ToTable("DaysTable");
                });

            modelBuilder.Entity("Domain.Models.Appointment.Meeting", b =>
                {
                    b.HasOne("Domain.Models.Termin.WorkingDay", "StartingWorkingDayDay")
                        .WithMany("meetings")
                        .HasForeignKey("StartingWorkingDayDayDayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("StartingWorkingDayDay");
                });

            modelBuilder.Entity("Domain.Models.Operation.Procedure", b =>
                {
                    b.HasOne("Domain.Models.Appointment.Meeting", null)
                        .WithMany("Procedures")
                        .HasForeignKey("MeetingMeetId");
                });

            modelBuilder.Entity("Domain.Models.Appointment.Meeting", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("Domain.Models.Termin.WorkingDay", b =>
                {
                    b.Navigation("meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
